Sprint1
Sonnik-pixel/SonnyDagouneau_2_19022021 pull request #1
Opened 2021-02-23 16:04 UTC by Sonnik-pixel

Je vais faire un test pour faire une demande de Pull Request, c'est à dire que je vais proposer et collaborer sur des modifications apportées à mon référentiel.

C'est une demande de vérification pour le moment et non une fusion (merge).

:soon: Validation...

2021-02-23 17:49 UTC, fmoy requested changes

2021-02-23 17:49 UTC, fmoy commented on index.html
> +
pas de saut de ligne

2021-02-23 17:49 UTC, fmoy commented on index.html
> +            <figure>
une figure va tjr avec une figcaption donc a voir si tu dois utiliser figure

2021-02-23 17:49 UTC, fmoy commented on index.html
> +            <nav>
il y a pas de role a ta nav ? via des attributs aria ?

2021-02-23 17:49 UTC, fmoy commented on index.html
> +                    <li><a href="#ancreheberg">Hébergements</a></li> <!--Faire id="ancreheberg" plus bas-->
camelCase les ID et tu dois voir les attributs obligatoires sur un lien et une image (voir title vs alt)

2021-02-23 17:49 UTC, fmoy commented on index.html
> +                    <li class="inscrire">S'inscrire</li>
une classe est présente plusieurs fois

2021-02-23 17:49 UTC, fmoy commented on index.html
> +        <main>
à laisser vide on y est pas encore

2021-02-23 17:49 UTC, fmoy commented on index.html
> +</html>
saut de ligne

2021-02-23 17:49 UTC, fmoy commented on index.html
> +
pas de saut pareil plus bas

2021-02-23 17:49 UTC, fmoy commented on style.css
> +
pas besoin de sauter autant de ligne

2021-02-23 17:49 UTC, fmoy commented on style.css
> +.logo {
le logo est présent qu'une fois donc tu le cibles comme dans le jeux css

2021-02-23 17:49 UTC, fmoy commented on style.css
> +    margin-top: 40px;
evites les px penses plutôt rem

2021-02-23 17:49 UTC, fmoy commented on style.css
> +ul a { /*Sélectionne toutes les balises <a>  situées à l'intérieur d'une balise <ul>*/
les commentaires c est haut dessus pas à coté

2021-02-23 17:49 UTC, fmoy commented on style.css
> +a:hover {
essaye d'utiliser les variables css

2021-02-24 09:15 UTC, Sonnik-pixel commented on index.html
> +
ok, j'ai enlevé tous les sauts de ligne sur mes fichiers html & css

2021-02-24 10:12 UTC, Sonnik-pixel commented on index.html
> +            <figure>
L'élément `figcaption` est optionnel ; s'il n'est pas présent, la figure n'aura pas de légende.
source : [https://developer.mozilla.org/fr/docs/Web/HTML/Element/figcaption](url)

Suppression de la balise `figure`

2021-02-24 10:33 UTC, Sonnik-pixel commented on index.html
> +            <nav>
Si tu veux dire par là de rajouter un attribut à ma balise, je viens de le faire :
`<nav class="navigation">`

2021-02-24 11:37 UTC, Sonnik-pixel commented on index.html
> +                    <li><a href="#ancreheberg">Hébergements</a></li> <!--Faire id="ancreheberg" plus bas-->
CamlCase : `#AncreHeberg`

TITLE = pour guider l'utilisateur sur ce qu'il voit, très peu référencé.
ALT = pour le référencement des images, affiche le texte et non l'image si connexion lente.

2021-02-24 13:42 UTC, Sonnik-pixel commented on index.html
> +                    <li class="inscrire">S'inscrire</li>
fmoy : _on evite l id et la classe si besoin de mutualiser le comportement_

Je ne voulais pas mutualiser le comportement, changer la couleur de "S'inscrire" sans changer la couleur de "Activités" et "Hébergements"

2021-02-24 13:43 UTC, Sonnik-pixel commented on index.html
> +        <main>
Vide ok, J'ai juste enlevé les sauts de ligne.

2021-02-24 13:44 UTC, Sonnik-pixel commented on index.html
> +</html>
C'est fait.

2021-02-24 13:44 UTC, Sonnik-pixel commented on index.html
> +
C'est fait.

2021-02-24 13:44 UTC, Sonnik-pixel commented on style.css
> +
C'est fait.

2021-02-24 13:57 UTC, Sonnik-pixel commented on style.css
> +.logo {
J'ai changé la class par un id vu que le logo est unique.

2021-02-24 13:59 UTC, Sonnik-pixel commented on style.css
> +    margin-top: 40px;
Remplacé par 2.5em

2021-02-24 14:07 UTC, Sonnik-pixel commented on style.css
> +ul a { /*Sélectionne toutes les balises <a>  situées à l'intérieur d'une balise <ul>*/
Fait.

2021-02-24 14:24 UTC, Sonnik-pixel commented on style.css
> +a:hover {
Utilisation de la balise `a:visited`

2021-03-03 17:48 UTC, fmoy approved these changes

2021-03-10 20:06 UTC, fmoy requested changes

2021-03-10 20:06 UTC, fmoy commented on index.html
> +    <link rel="stylesheet" href="style.css">
ton style en dernier ton reset en premier

2021-03-10 20:06 UTC, fmoy commented on index.html
> +        <div class="nav1"><a class="lien1" href="#"><img src="https://github.com/audreydiez/AudreyDiez_2_02122020/blob/master/assets/images/logo/Reservia@3x.png?raw=tr   ue" alt="Logo" /></a></div>
à héberger dans ton dossier image

2021-03-10 20:06 UTC, fmoy commented on index.html
> +        <div class="nav1"><a class="lien1" href="#"><img src="https://github.com/audreydiez/AudreyDiez_2_02122020/blob/master/assets/images/logo/Reservia@3x.png?raw=tr   ue" alt="Logo" /></a></div>
ne pas utiliser des class te creer tes propres attributs
```html
<a target="_blank" data-nav="register">lien</a>
```
```css
[data-nav='register'] {
      order: 2;
}
```

2021-03-10 20:06 UTC, fmoy commented on index.html
> +        <div class="nav1"><a class="lien1" href="#"><img src="https://github.com/audreydiez/AudreyDiez_2_02122020/blob/master/assets/images/logo/Reservia@3x.png?raw=tr   ue" alt="Logo" /></a></div>
remplacer ta balise div par <nav> et utiliser éventuellement un ul>li a la place de div

2021-03-10 20:06 UTC, fmoy commented on index.html
> +<!--
à retirer

2021-03-10 20:06 UTC, fmoy commented on reset.css
> +}
sauter une ligne

2021-03-10 20:06 UTC, fmoy commented on reset.css
> +@import url('https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600&display=swap');
à placer dans ta feuille style.css commune

2021-03-10 20:06 UTC, fmoy commented on style.css
> +  @media (max-width: 500px) {
Déplacer ce code dans une feuille à part et revoir les valeurs de tes breakpoints (pour le moment un aspect mobile et desktop) plus tard tablette si besoin

2021-03-10 20:06 UTC, fmoy commented on style.css
> +
saut de ligne

2021-03-10 20:06 UTC, fmoy commented on style.css
> +  .nav1 {
mettre ça dans une autre feuille de style avec media desktop

2021-03-10 20:06 UTC, fmoy commented on style.css
> +    flex-basis: 50%;
utiliser weight vh

2021-03-10 20:06 UTC, fmoy commented on style.css
> +    order: 2;
order à retirer, met juste un seul order sur le bon élément.

2021-03-10 20:06 UTC, fmoy commented on style.css
> +    /*width: 100px;*/
à retirer

2021-03-10 20:06 UTC, fmoy commented on style.css
> +  .nav2 {
ajouter un commentaire sur chaque "section" ou "block" du site
```css
/***********************/
/********* MENU ********/
/***********************/
```

2021-03-10 20:06 UTC, fmoy commented on style.css
> +  .lien4 {
Si chaque lien a la même propriété, faire une déclaration générique pour éviter de la redondance de code
```css
ul li {
    display: flex;
}
```

2021-03-11 13:39 UTC, Sonnik-pixel commented on index.html
> +    <link rel="stylesheet" href="style.css">
Ok

2021-03-11 14:07 UTC, Sonnik-pixel commented on index.html
> +        <div class="nav1"><a class="lien1" href="#"><img src="https://github.com/audreydiez/AudreyDiez_2_02122020/blob/master/assets/images/logo/Reservia@3x.png?raw=tr   ue" alt="Logo" /></a></div>
Hébergement local ok
<nav>
<ul>
<li></li>
</ul>
</nav>

2021-03-11 14:12 UTC, Sonnik-pixel commented on index.html
> +<!--
Saut de ligne retiré

2021-03-11 14:13 UTC, Sonnik-pixel commented on reset.css
> +}
Saut de ligne ok

2021-03-11 14:21 UTC, Sonnik-pixel commented on style.css
> +    order: 2;
Ok juste un order !

2021-03-11 14:22 UTC, Sonnik-pixel commented on style.css
> +    /*width: 100px;*/
J'ai juste laissé le display: flex;

2021-03-11 14:35 UTC, Sonnik-pixel commented on style.css
> +  .nav2 {
ok 

  /**************************/
  /****** HADER NAVBAR ******/
  /**************************/

2021-03-11 14:38 UTC, Sonnik-pixel commented on style.css
> +  .lien4 {
Ok

2021-03-11 14:57 UTC, Sonnik-pixel commented on index.html
> +        <div class="nav1"><a class="lien1" href="#"><img src="https://github.com/audreydiez/AudreyDiez_2_02122020/blob/master/assets/images/logo/Reservia@3x.png?raw=tr   ue" alt="Logo" /></a></div>
'''<li class="nav3"><a data-nav="lien3" href="#">Activités</a></li>'''

'''[data-nav='lien3']'''

2021-03-11 15:06 UTC, Sonnik-pixel commented on style.css
> +    flex-basis: 50%;
Plutôt width tu voulais dire ?

2021-03-11 16:01 UTC, Sonnik-pixel commented on index.html
> +    <link rel="stylesheet" href="style.css">
Ajout en dernière ligne de `<link rel="stylesheet" href="mobile.css">`

2021-03-11 16:41 UTC, Sonnik-pixel commented on style.css
> +    flex-basis: 50%;
J'essaie des longueurs etc rien n'y fait...

2021-04-07 18:24 UTC, merged